/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.freelas.etiquetas;

import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rodri
 */
public class TelaCadastroEtiquetas extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastroEtiquetas
     */
    
    private List<Etiqueta> listaEtiquetas;
    private EtiquetaDAO etiquetaDAO;
    
    public TelaCadastroEtiquetas() {
        initComponents();
        
        try {
             this.etiquetaDAO  = new EtiquetaDAO();
         } catch (SQLException ex) {
             JOptionPane.showMessageDialog(this, "Erro ao ler o arquivo de banco de dados!");
             Logger.getLogger(Etiquetas.class.getName()).log(Level.SEVERE, null, ex);
         }
        
        listaEtiquetas =  etiquetaDAO.getListaDeEtiquetas();
        
        atualizarTabela(listaEtiquetas);
        
   

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaEtiquetas = new javax.swing.JTable();
        inputCodigo = new javax.swing.JTextField();
        inputLabel = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnExcluirEtiqueta = new javax.swing.JButton();
        btnCadastrarEtiqueta1 = new javax.swing.JButton();

        tabelaEtiquetas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Label"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabelaEtiquetas.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabelaEtiquetas);

        jLabel1.setText("Código");

        jLabel2.setText("Label");

        btnExcluirEtiqueta.setText("Excluir");
        btnExcluirEtiqueta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirEtiquetaActionPerformed(evt);
            }
        });

        btnCadastrarEtiqueta1.setText("Cadastrar");
        btnCadastrarEtiqueta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarEtiqueta1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                                .addComponent(inputCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(inputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnExcluirEtiqueta, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCadastrarEtiqueta1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(inputCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCadastrarEtiqueta1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(inputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnExcluirEtiqueta, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void atualizarTabela(List<Etiqueta> lista){
    
         DefaultTableModel modeloTabela = (DefaultTableModel) tabelaEtiquetas.getModel();
         
         // Limpa a tabela
         modeloTabela.setRowCount(0);
         
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment( JLabel.LEFT );
        
        tabelaEtiquetas.getColumnModel().getColumn(0).setCellRenderer( centerRenderer );
        tabelaEtiquetas.getColumnModel().getColumn(1).setCellRenderer( centerRenderer );
        
        
         for(Etiqueta et : lista){
            Object[] dados = {et.getCodigo(),et.getLabel()};
            modeloTabela.addRow(dados);
         
         
         }
         
         modeloTabela.fireTableDataChanged();
    
    
    }
    
    
    private void btnExcluirEtiquetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirEtiquetaActionPerformed
   
        int linhaSelecionada =  tabelaEtiquetas.getSelectedRow();
     
        if(linhaSelecionada < 0){
             JOptionPane.showMessageDialog(this, "Nenhuma linha selecionada para exclusão!");
               return;
        }
        
       String codigo =  tabelaEtiquetas.getValueAt(linhaSelecionada, 0).toString();
       String label =  tabelaEtiquetas.getValueAt(linhaSelecionada, 1).toString();
       
        try {
            etiquetaDAO.deleteEtiqueta(codigo);
            JOptionPane.showMessageDialog(this, "Etiqueta excluída com sucesso!");
            listaEtiquetas =  etiquetaDAO.getListaDeEtiquetas();
            atualizarTabela(listaEtiquetas);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
            
        }

        
    }//GEN-LAST:event_btnExcluirEtiquetaActionPerformed

    private void btnCadastrarEtiqueta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarEtiqueta1ActionPerformed
        String codigo = (String) this.inputCodigo.getText();
        String label = (String) this.inputLabel.getText();
        
        if(codigo == null || codigo.equals("") || label == null || label.equals("")){
            JOptionPane.showMessageDialog(this, "Insira os dados de código e label corretamente. Não pode ser vazio.");
            return;
        }
        
        Etiqueta etiqueta = new Etiqueta(codigo, label, "0");
        try {
            this.etiquetaDAO.insertEtiqueta(etiqueta);
        } catch (SQLException ex) {            
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        
        listaEtiquetas =  etiquetaDAO.getListaDeEtiquetas();
        
        atualizarTabela(listaEtiquetas);
        
        
        this.inputCodigo.setText("");
        this.inputLabel.setText("");
    }//GEN-LAST:event_btnCadastrarEtiqueta1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroEtiquetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroEtiquetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroEtiquetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroEtiquetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroEtiquetas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarEtiqueta1;
    private javax.swing.JButton btnExcluirEtiqueta;
    private javax.swing.JTextField inputCodigo;
    private javax.swing.JTextField inputLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaEtiquetas;
    // End of variables declaration//GEN-END:variables
}
